### ISSUE TITLE
Resolve security alerts

### ISSUE THREAD

**Issue by dim** [bsm/go-benchmark#6]

**Comment by dim** [comment]
Still something going on https://github.com/bsm/go-benchmark/security/dependabot

**Comment by dim** [comment]
Looks like a dep is importing an old lib. Which one is it?

**Comment by mxmCherry** [comment]
Go doesn't seem to upgrade everything it sees in go.mod.

Looks like rm-ing go.mod's require section + rm-ing go.sum got rid of x/net@v0.17.0

PR-ed in https://github.com/bsm/go-benchmark/pull/13

**Comment by mxmCherry** [comment]
Actually fixed by https://github.com/bsm/go-benchmark/pull/14

Needed explicit `go get -u PKGNAME` for that, or it pulled stuff from other deps' deps.
